// <auto-generated />
using System;
using Expense_tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expense_tracker.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20250805112338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Expense_tracker.Models.Expense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("TEXT");

                    b.Property<string>("CATEGORY")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CREATED_DATE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Expense_tracker.Models.ExpenseCategories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CATEGORY_NAME")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CREATED_DATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
